#!/usr/bin/perl

# (c) 2017 Jim Salter. Licensed GPLv3.

# this software is licensed for use under the Free Software Foundation's GPL v3.0 license, as retrieved
# from http://www.gnu.org/licenses/gpl-3.0.html on 2014-11-17.  A copy should also be available in this
# project's Git repository at https://github.com/jimsalterjrs/network-testing/blob/master/LICENSE.

use strict;
use Config::IniFiles;   # read samba-style conf file
use Data::Dumper;       # debugging - print contents of hash

my $conf_file = './multiclient.conf';
my $sshcmd = '/usr/bin/ssh';

# load test configs from multiclient.conf
tie my %ini, 'Config::IniFiles', ( -file => $conf_file ) or die "FATAL: cannot load $conf_file.";

# populate %devices,%directives from $ini{'devices'} for easier access later
my %devices;
my %directives;
foreach my $device (keys %{ $ini{'devices'} }) {
	$devices{$device} = $ini{'devices'}{$device};
}
foreach my $device (keys %{ $ini{'directives'} }) {
	$directives{$device} = $ini{'directives'}{$device};
	if ($directives{$device} =~ /^\$/) {
		# it's an alias, so populate it from the aliases table
		$directives{$device} = $ini{'aliases'}{$directives{$device}};
	}
}


# establish SSH control sessions for each device
foreach my $device (sort keys %devices) { 
	my $socket = "/tmp/multiclient-$device-" . time();
	open FH, "$sshcmd -M -S $socket -o ControlPersist=5m $devices{$device} exit |";
	close FH;
}

# establish clock is synced at each device
foreach my $device (sort keys %devices) { 
	my $cmd = "/bin/date +%s";
	my $now = time();
	my $sync = `$sshcmd $devices{$device} $cmd`;
	if ( abs($now - $sync) <2 ) {
		print "Device $device at $devices{$device} is in sync with me.\n";
	} else {
		my $delta = $now-$sync;
		print "Device $device at $devices{$device} is $delta seconds off from my clock.\n";
	}
}

my $when = time()+10;

# loop through the directives given
foreach my $device (sort keys %directives) {
	#print "$device is at $devices{$device} and needs to whenits $when $directives{$device} .\n";
	my $cmd = "ssh root\@$devices{$device} whenits $when $directives{$device}";
	print "$cmd\n";
	system $cmd;
}
