#!/usr/bin/perl

# (c) 2017 Jim Salter. Licensed GPLv3.

# whenits [unixtime] [command] - execute the given command when the system reaches the unix time specifed as the first argument.

# this software is licensed for use under the Free Software Foundation's GPL v3.0 license, as retrieved
# from http://www.gnu.org/licenses/gpl-3.0.html on 2014-11-17.  A copy should also be available in this
# project's Git repository at https://github.com/jimsalterjrs/network-testing/blob/master/LICENSE.


use Time::HiRes qw ( usleep gettimeofday );

my $exectime = $ARGV[0];

my ($seconds,$microseconds) = gettimeofday();
my $currenttime = "$seconds." . sprintf ("%.06d", $microseconds);
my $usleeptime = ($exectime - $currenttime) * 1000000;

# give ourselves a 2 tenths of a second window since usleep is only so accurate
$usleeptime -= 200000;
print "Sleeping " . ($usleeptime / 1000000) . " seconds.\n";
usleep $usleeptime;

my $time = time();
while ($time < $exectime) { $time = time() };

($seconds,$microseconds) = gettimeofday();
$currenttime = "$seconds." . sprintf ("%.06d", $microseconds);
print "time is: $currenttime\n";
