#!/usr/bin/perl

# apt install liblog-log4perl-perl liblog-dispatch-perl
use Log::Log4perl qw(get_logger :levels);

# user-defined variable initialization
my $NETID = "your Network-Manager wifi profile name";
my $GATEWAY = "192.168.0.1";
my $IFNAME = "usbnic0";

# configure logging
my $logger = get_logger();
$logger->level($WARN);
my $appender = Log::Log4perl::Appender->new(
	"Log::Dispatch::File",
	filename => "/var/log/syslog",
	mode => "append",
);

# standard syslog format
my $layout =
      Log::Log4perl::Layout::PatternLayout->new(
	"%d %H %F{1}[%P]: %p - %m%n"
);
$appender->layout($layout);
$logger->add_appender($appender);

# check for connectivity to network gateway
my $up = `/bin/ping -c1 -W1 $GATEWAY 2>&1`;

if ($up =~ "unreachable" || $up =~ "100% packet loss") {
	# connection down - bring it back up
	print "Connection down - restarting wifi on intel0...\n";
	print `/usr/bin/nmcli c up id "$NETID" ifname $IFNAME`;
	$logger->error("monitored wifi restarted");
	#print `/usr/bin/aplay /usr/share/orage/sounds/Boiling.wav`;
} else {
	# connection should be up - nothing to do
}

